#!/usr/bin/env bash
# One-time: fixed URL (e.g. faceswap.yourdomain.com) via named Cloudflare tunnel.
# Requires: domain on Cloudflare (free plan), cloudflared installed (brew install cloudflared).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="$ROOT/deploy/cloudflared/config.yml"
CRED_DIR="${HOME}/.cloudflared"
TUNNEL_NAME="face-swap"

resolve_cloudflared() {
  for candidate in cloudflared /opt/homebrew/bin/cloudflared /usr/local/bin/cloudflared; do
    if command -v "$candidate" >/dev/null 2>&1; then
      command -v "$candidate"
      return
    fi
    if [[ -x "$candidate" ]]; then
      echo "$candidate"
      return
    fi
  done
  return 1
}

CF="$(resolve_cloudflared)" || {
  echo "Install cloudflared: brew install cloudflared"
  exit 1
}

if [[ -f "$CONFIG" ]]; then
  echo "Already configured: $CONFIG"
  grep -E 'hostname:|credentials-file:' "$CONFIG" || true
  echo ""
  echo "Start the app with: bash deploy/start-permanent-mac.sh"
  exit 0
fi

echo "=== Permanent Cloudflare URL (one-time setup) ==="
echo ""
echo "You need a domain using Cloudflare DNS (e.g. yourdomain.com on Cloudflare free plan)."
echo "You will pick a subdomain, e.g. faceswap.yourdomain.com"
echo ""
read -r -p "Enter full hostname (e.g. faceswap.yourdomain.com): " HOSTNAME
if [[ -z "$HOSTNAME" ]] || [[ "$HOSTNAME" != *.* ]]; then
  echo "Invalid hostname."
  exit 1
fi

mkdir -p "$CRED_DIR"
echo ""
echo "Step 1/4: Log in to Cloudflare (browser opens)..."
"$CF" tunnel login

echo ""
echo "Step 2/4: Create tunnel '$TUNNEL_NAME'..."
if "$CF" tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
  echo "Tunnel '$TUNNEL_NAME' already exists — using it."
else
  "$CF" tunnel create "$TUNNEL_NAME"
fi

TUNNEL_ID="$("$CF" tunnel list -o json 2>/dev/null | python3 -c "
import json, sys
name = sys.argv[1]
data = json.load(sys.stdin)
for t in data:
    if t.get('name') == name:
        print(t['id'])
        break
" "$TUNNEL_NAME" 2>/dev/null || true)"

if [[ -z "$TUNNEL_ID" ]]; then
  # Fallback: parse text table (id is first column)
  TUNNEL_ID="$("$CF" tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2 == n { print $1; exit }')"
fi

CREDS="${CRED_DIR}/${TUNNEL_ID}.json"
if [[ ! -f "$CREDS" ]]; then
  # Some installs name the file after tunnel name
  if [[ -f "${CRED_DIR}/${TUNNEL_NAME}.json" ]]; then
    CREDS="${CRED_DIR}/${TUNNEL_NAME}.json"
  else
    echo "Could not find credentials in $CRED_DIR"
    echo "List tunnels: $CF tunnel list"
    ls -la "$CRED_DIR" 2>/dev/null || true
    exit 1
  fi
fi

echo ""
echo "Step 3/4: Write $CONFIG"
mkdir -p "$(dirname "$CONFIG")"
cat >"$CONFIG" <<EOF
# Generated by deploy/setup-permanent-tunnel-mac.sh — do not commit (gitignored).
tunnel: ${TUNNEL_ID}
credentials-file: ${CREDS}

ingress:
  - hostname: ${HOSTNAME}
    service: http://127.0.0.1:8000
  - service: http_status:404
EOF

echo ""
echo "Step 4/4: DNS — point $HOSTNAME to this tunnel..."
"$CF" tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" || {
  echo ""
  echo "If route dns failed, add manually in Cloudflare dashboard:"
  echo "  CNAME  ${HOSTNAME%%.*}  ->  ${TUNNEL_ID}.cfargotunnel.com  (proxied)"
  echo "  (Use the subdomain label that matches your hostname.)"
}

echo ""
echo "=== Done ==="
echo "Your fixed URL: https://${HOSTNAME}"
echo ""
echo "Each time you want remote access, run:"
echo "  bash deploy/start-permanent-mac.sh"
echo ""
echo "Keep the Mac awake and that terminal open (same as quick tunnel)."
